policy:
  approval:
    - tests passed

approval_rules:
  - name: tests passed
    requires:
      conditions:
        has_status:
          conclusions: ["success", "skipped"]
          statuses:
            - "build-test-release (component-a)"
            - "build-test-release (component-b)"
