policy:
  approval:
    - tests passed

approval_rules:
  - name: tests passed
    requires:
      conditions:
        has_workflow_status:
          conclusions: ["success", "skipped"]
          statuses:
            - ".github/workflows/component-a.yaml"
            - ".github/workflows/component-b.yaml"
