policy:
  approval:
    - and:
        - test passed
        - no test required

approval_rules:
  - name: test passed
    requires:
      conditions:
        has_status:
          conclusions: ["success", "skipped"]
          statuses:
            - "test"
    if:
      changed_files: &test_required_files
        paths:
          - "^.github/.*$"

  - name: no test required
    if:
      no_changed_files: *test_required_files
