name: CI

on:
  pull_request:

jobs:
  build-test-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component:
          - component-a
          - component-b
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Fake test
        working-directory: ../..
        run: |
          sleep 15
          ./${{ env.COMPONENT }}/src.sh
        env:
          COMPONENT: ${{ matrix.component }}
