name: component-b

on:
  pull_request:
    paths:
      - ".github/workflows/component-b.yaml"
      - "component-b/**"

jobs:
  build-test-release:
    name: build-test-release (component-b)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Fake test
        run: |
          sleep 15
          ./component-b/src.sh
